interface=dswifi0
bind-interfaces

# DHCP
dhcp-range=192.168.33.100,192.168.33.200,255.255.255.0,12h
dhcp-option=6,192.168.33.1

# SET UPSTREAM DNS SERVER
server=192.168.1.1

# DNS overrides C:
address=/nintendowifi.net/192.168.33.1

# not using these features
no-resolv
no-hosts
